services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
      - shared_scripts:/shared
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_MODEL=gemma3:1b
    entrypoint: ["/bin/bash", "/shared/entrypoint.sh"]
    restart: unless-stopped
    # Uncomment the following lines if you have a GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  endless-wiki:
    image: xanderstrike/endless-wiki:latest
    container_name: endless-wiki
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=gemma3:1b
      - PORT=8080
    volumes:
      - shared_scripts:/shared
    depends_on:
      - ollama
    restart: unless-stopped
    command: sh -c "cp /root/entrypoint.sh /shared/ && ./main"

volumes:
  ollama_data:
  shared_scripts:
